---
- name: Install NFS server
  apt:
    pkg=nfs-kernel-server
    state=present

- name: Release resources for local configuration
  service:
    name={{ item }}
    state=stopped
  notify: restart heartbeat
  with_items:
    - heartbeat
    - drbd

- name: Stop and disable NFS kernel server
  service:
    name={{ item }}
    enabled=no
    state=stopped
  notify: restart heartbeat
  with_items:
    - nfs-kernel-server
    - nfs-common

- name: Configure NFS exports
  template:
    src=exports.j2
    dest=/etc/exports
  notify: restart heartbeat

- name: Create data directory
  file:
    path=/data
    state=directory

- name: Check data symlink
  stat:
    path=/var/lib/nfs
  register: stats

- name: Prepare NFS exports on DRBD device
  include: on_primary.yml

- name: Remove the NFS metadata
  file:
    path=/var/lib/nfs/
    state=absent
  when: "primary is not defined and stats.stat.isdir"
  notify: restart heartbeat

- name: Link the NFS metadata from its original location
  file:
    src=/data/nfs/
    dest=/var/lib/nfs
    state=link
  notify: restart heartbeat
