---
- name: Install NFS server
  apt:
    pkg: nfs-kernel-server
    state: present

- name: Stop and disable NFS kernel server
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  notify: restart heartbeat
  with_items:
    - nfs-kernel-server
    - nfs-common

- name: Configure NFS exports
  template:
    src: exports.j2
    dest: /etc/exports
  notify: restart heartbeat

- name: Configure NFS mountd
  copy:
    src: nfs-kernel-server
    dest: /etc/default/nfs-kernel-server
    owner: root
    group: root
    mode: 0644

- name: Create data directory
  file:
    path: /data
    state: directory

- name: Check data symlink
  stat:
    path: /var/lib/nfs
  register: stats

- name: Determine primary
  shell: "drbdadm role {{ group_names[0] }}"
  register: drbdstate

- name: Set primary if needed
  shell: "drbdadm primary {{ group_names[0] }}"
  register: primaryset
  when: "primary is defined and 'Primary' not in drbdstate.stdout.split('/')"

- name: Prepare NFS exports on DRBD device
  include: on_primary.yml
  when: "drbdstate.stdout.split('/')[0] == 'Primary' or primaryset.changed"

- name: Remove the NFS metadata
  file:
    path: /var/lib/nfs/
    state: absent
  when: "drbdstate.stdout.split('/')[0] != 'Primary' and stats.stat.isdir"
  notify: restart heartbeat

- name: Link the NFS metadata from its original location
  file:
    src: /data/nfs/
    dest: /var/lib/nfs
    state: link
    force: yes
  notify: restart heartbeat
