---
- name: Temporary mount of the DRBD device
  mount:
    name: /data
    src: /dev/drbd0
    fstype: ext4
    state: mounted
  notify: restart heartbeat

- name: Create exported directory
  file:
    path: /data/export
    state: directory
  notify: restart heartbeat

- name: Move the NFS metadata to the DRBD device
  shell: cp -r /var/lib/nfs/ /data/ && rm -rf /var/lib/nfs/
  when: stats.stat.isdir
  notify: restart heartbeat

- name: Unmount the DRBD device
  mount:
    name: /data
    src: /dev/drbd0
    fstype: ext4
    state: unmounted
  notify: restart heartbeat
